[phases.setup]
# Use Node 20 and install Chromium with all required dependencies
nixPkgs = ["nodejs-20_x", "chromium", "nss", "freetype", "harfbuzz", "ca-certificates", "ttf-freefont", "fontconfig"]

[phases.install]
# Install dependencies from root (monorepo setup)
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
# Build the Next.js web app
cmds = ["cd apps/web && npm run build"]

[start]
# Start production server
cmd = "cd apps/web && npm start"

[variables]
# Puppeteer configuration - use system Chromium
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*-chromium-*/bin/chromium"
# Chromium flags for Railway environment
PUPPETEER_ARGS = "--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-gpu"

