name: Phase 1 - Basic CI

# PHASE 1: Just lint and type-check on PRs
# Safe, non-invasive, no auto-deployment

on:
  pull_request:
    branches: [main, develop]

jobs:
  # Job 1: Lint and Type Check
  lint-and-typecheck:
    name: Lint & Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./apps/web

      - name: Run ESLint
        run: npm run lint
        working-directory: ./apps/web
        continue-on-error: true  # Don't fail build, just warn

      - name: Run TypeScript type check
        run: npm run type-check
        working-directory: ./apps/web
        continue-on-error: true  # Don't fail build, just warn

  # Job 2: Summary
  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    if: always()

    steps:
      - name: Display results
        run: |
          echo "📊 Phase 1 CI Results"
          echo "===================="
          echo "Lint & Type Check: ${{ needs.lint-and-typecheck.result }}"
          echo ""
          echo "ℹ️  This is Phase 1 - Basic validation only"
          echo "ℹ️  No auto-deployment, no blocking"
          echo "ℹ️  Just checking code quality"

