name: Deploy to Railway

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./apps/web

      - name: Run pre-deployment checks
        run: |
          echo "🔍 Running pre-deployment checks..."
          npm run type-check
          npm run lint
          echo "✅ Pre-deployment checks passed"
        working-directory: ./apps/web

      - name: Build application
        run: npm run build
        working-directory: ./apps/web
        env:
          # Use placeholder values for build test
          NEXT_PUBLIC_SUPABASE_URL: https://placeholder.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: placeholder-key
          NEXT_PUBLIC_SITE_URL: https://placeholder.com
          NODE_ENV: production

      - name: Deployment notification
        run: |
          echo "🚀 Deployment triggered to Railway"
          echo "📊 Branch: ${{ github.ref }}"
          echo "📝 Commit: ${{ github.sha }}"
          echo "👤 Author: ${{ github.actor }}"
          echo ""
          echo "Railway will automatically deploy this commit."
          echo "Monitor deployment at: https://railway.app"

      # Optional: Add Railway CLI deployment
      # Uncomment and add RAILWAY_TOKEN to GitHub Secrets if you want to trigger deployment via CLI
      # - name: Install Railway CLI
      #   run: npm install -g @railway/cli
      
      # - name: Deploy to Railway
      #   run: railway up
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Post-deployment checklist
        run: |
          echo "📋 Post-deployment checklist:"
          echo "- [ ] Check Railway deployment logs"
          echo "- [ ] Verify https://www.travelblogr.com loads"
          echo "- [ ] Test user registration/login"
          echo "- [ ] Test critical features"
          echo "- [ ] Monitor for errors (10-15 minutes)"

